### ISSUE TITLE
announce when players enter your room, or items are dropped in the room

### ISSUE THREAD

**Issue by shapr** [cdsmith/ourmud#5]

**Comment by cdsmith** [comment]
To do this, we really want to have a notification queue attached to every player who is logged in to the game.  Then, when something happens that affects a player, a notification can be added to their queue.  Each client should ensure that a thread occasionally polls its queue, and sends any notifications that are waiting.

These notification queues shouldn't really be persisted across server runs, so they aren't part of the `World`.  They would be reset if the server is restarted.  So I guess we really want some kind of `Map (Ref Player) NotificationQueue` that lives outside of the world.
